# Generated by Django 5.0.1 on 2025-12-08 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0003_epic_created_by_epic_updated_by_project_created_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_states",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom workflow states for this project",
                    ),
                ),
                (
                    "state_transitions",
                    models.JSONField(
                        blank=True, default=dict, help_text="Allowed state transitions"
                    ),
                ),
                (
                    "board_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Board column configuration (order, visibility, etc.)",
                    ),
                ),
                (
                    "max_story_points_per_story",
                    models.IntegerField(
                        default=21, help_text="Maximum story points allowed per story"
                    ),
                ),
                (
                    "min_story_points_per_story",
                    models.IntegerField(
                        default=1, help_text="Minimum story points allowed per story"
                    ),
                ),
                (
                    "story_point_scale",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Allowed story point values (e.g., Fibonacci: [1,2,3,5,8,13,21])",
                    ),
                ),
                (
                    "max_story_points_per_sprint",
                    models.IntegerField(
                        default=40,
                        help_text="Maximum total story points allowed per sprint",
                    ),
                ),
                (
                    "story_points_required",
                    models.BooleanField(
                        default=False,
                        help_text="Require story points before moving to 'In Progress'",
                    ),
                ),
                (
                    "default_sprint_duration_days",
                    models.IntegerField(
                        default=14, help_text="Default sprint duration in days"
                    ),
                ),
                (
                    "sprint_start_day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                        help_text="Default day of week for sprint start",
                    ),
                ),
                (
                    "auto_close_sprints",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically close sprints when end date passes",
                    ),
                ),
                (
                    "allow_overcommitment",
                    models.BooleanField(
                        default=False,
                        help_text="Allow sprints to exceed max story points",
                    ),
                ),
                (
                    "default_board_view",
                    models.CharField(
                        choices=[
                            ("kanban", "Kanban"),
                            ("list", "List"),
                            ("table", "Table"),
                            ("timeline", "Timeline"),
                            ("calendar", "Calendar"),
                        ],
                        default="kanban",
                        help_text="Default board view",
                        max_length=20,
                    ),
                ),
                (
                    "swimlane_grouping",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("assignee", "Assignee"),
                            ("epic", "Epic"),
                            ("priority", "Priority"),
                            ("component", "Component"),
                            ("custom_field", "Custom Field"),
                        ],
                        default="none",
                        help_text="Swimlane grouping option",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "swimlane_custom_field",
                    models.CharField(
                        blank=True,
                        help_text="Custom field name for swimlane grouping",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "card_display_fields",
                    models.JSONField(
                        blank=True, default=list, help_text="Fields to display on cards"
                    ),
                ),
                (
                    "card_color_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("priority", "Priority"),
                            ("epic", "Epic"),
                            ("type", "Story Type"),
                            ("component", "Component"),
                            ("custom", "Custom"),
                        ],
                        default="priority",
                        help_text="Card color coding rule",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "automation_rules",
                    models.JSONField(
                        blank=True, default=list, help_text="Workflow automation rules"
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Project notification preferences",
                    ),
                ),
                (
                    "permission_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Project-specific permission overrides",
                    ),
                ),
                (
                    "integration_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Project-specific integration settings",
                    ),
                ),
                (
                    "custom_fields_schema",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Schema for custom fields in this project",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation rules for stories/tasks",
                    ),
                ),
                (
                    "analytics_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Analytics and reporting preferences",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_project_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Configuration",
                "verbose_name_plural": "Project Configurations",
                "db_table": "project_configurations",
            },
        ),
    ]
