# Generated by Django 5.0.1 on 2025-12-08 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_add_tags_and_additional_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "reactions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Emoji reactions to the comment",
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_story_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_story_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment for threading",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.storycomment",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.userstory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_story_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Comment",
                "verbose_name_plural": "Story Comments",
                "db_table": "story_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mention_text",
                    models.CharField(
                        help_text="The actual @mention text (e.g., '@john.doe')",
                        max_length=200,
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the mention has been read by the user",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False, help_text="Whether notification was sent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mentions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        help_text="User who was mentioned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        help_text="Story where mention occurred",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="projects.userstory",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Comment where mention occurred (if implemented)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="projects.storycomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mention",
                "verbose_name_plural": "Mentions",
                "db_table": "mentions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="storycomment",
            index=models.Index(
                fields=["story", "created_at"], name="story_comme_story_i_f3cd72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storycomment",
            index=models.Index(
                fields=["parent"], name="story_comme_parent__644c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(
                fields=["mentioned_user", "read"], name="mentions_mention_e5e666_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(fields=["story"], name="mentions_story_i_e255f4_idx"),
        ),
        migrations.AddIndex(
            model_name="mention",
            index=models.Index(
                fields=["created_at"], name="mentions_created_38178d_idx"
            ),
        ),
    ]
