# Generated by Django 5.0.1 on 2025-12-08 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_storycomment_mention_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="story_attachments/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the attachment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_story_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.userstory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_story_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Attachment",
                "verbose_name_plural": "Story Attachments",
                "db_table": "story_attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["story", "created_at"],
                        name="story_attac_story_i_4f1e55_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("blocks", "Blocks"),
                            ("blocked_by", "Blocked By"),
                            ("relates_to", "Relates To"),
                            ("duplicates", "Duplicates"),
                            ("depends_on", "Depends On"),
                        ],
                        default="blocks",
                        help_text="Type of dependency relationship",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the dependency"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the dependency has been resolved",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_story_dependencies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_dependencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_story",
                    models.ForeignKey(
                        help_text="Story that has the dependency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_dependencies",
                        to="projects.userstory",
                    ),
                ),
                (
                    "target_story",
                    models.ForeignKey(
                        help_text="Story that is depended upon",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_dependencies",
                        to="projects.userstory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_story_dependencies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Dependency",
                "verbose_name_plural": "Story Dependencies",
                "db_table": "story_dependencies",
                "indexes": [
                    models.Index(
                        fields=["source_story", "dependency_type"],
                        name="story_depen_source__b3bcec_idx",
                    ),
                    models.Index(
                        fields=["target_story", "dependency_type"],
                        name="story_depen_target__bbdb35_idx",
                    ),
                    models.Index(
                        fields=["resolved"], name="story_depen_resolve_d289af_idx"
                    ),
                ],
                "unique_together": {
                    ("source_story", "target_story", "dependency_type")
                },
            },
        ),
    ]
