# Generated by Django 5.0.1 on 2025-12-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_dde14f_idx",
            old_name="notificatio_recipie_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_2d3764_idx",
            old_name="notificatio_recipie_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_notific_498289_idx",
            old_name="notificatio_notific_idx",
        ),
    ]
