# Generated by Django 5.0.1 on 2025-12-09 02:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0009_rename_notificatio_recipie_idx_notificatio_recipie_dde14f_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="component",
            field=models.CharField(
                blank=True,
                help_text="Component or module this task belongs to",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Color-coded labels for visual grouping (e.g., [{'name': 'Urgent', 'color': '#red'}])",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent task for sub-tasks",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="projects.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                help_text="Task completion percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="story",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent story (null for standalone tasks)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.userstory",
            ),
        ),
    ]
