# Generated by Django 5.0.1 on 2025-12-09 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_task_component_task_labels_task_parent_task_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("trivial", "Trivial"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("p0", "P0 - Blocker"),
                            ("p1", "P1 - Critical"),
                            ("p2", "P2 - High"),
                            ("p3", "P3 - Medium"),
                            ("p4", "P4 - Low"),
                        ],
                        default="p3",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed"),
                            ("wont_fix", "Won't Fix"),
                            ("duplicate", "Duplicate"),
                            ("invalid", "Invalid"),
                            ("works_as_designed", "Works as Designed"),
                        ],
                        help_text="Resolution when bug is closed/resolved",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                            ("local", "Local"),
                        ],
                        default="production",
                        help_text="Environment where bug was found",
                        max_length=20,
                    ),
                ),
                (
                    "reproduction_steps",
                    models.TextField(
                        blank=True, help_text="Steps to reproduce the bug"
                    ),
                ),
                (
                    "expected_behavior",
                    models.TextField(blank=True, help_text="Expected behavior"),
                ),
                (
                    "actual_behavior",
                    models.TextField(blank=True, help_text="Actual behavior observed"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing and filtering bugs",
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Color-coded labels for visual grouping",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True,
                        help_text="Component or module where bug occurs",
                        max_length=100,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Target date for bug resolution",
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the bug was resolved", null=True
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the bug was closed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "verbose_name": "Bug",
                "verbose_name_plural": "Bugs",
                "db_table": "bugs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                help_text="User who receives the notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectconfiguration",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="projectconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_project_configurations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                default="medium", help_text="Priority level", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                default="todo",
                help_text="Workflow state (validated against project configuration)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userstory",
            name="component",
            field=models.CharField(
                blank=True,
                help_text="Component or module this story belongs to",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userstory",
            name="labels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Color-coded labels for visual grouping",
            ),
        ),
        migrations.AlterField(
            model_name="userstory",
            name="priority",
            field=models.CharField(
                default="medium", help_text="Priority level", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userstory",
            name="status",
            field=models.CharField(
                default="backlog",
                help_text="Workflow state (validated against project configuration)",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["story", "status"], name="tasks_story_i_711895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["parent_task", "status"], name="tasks_parent__8cce8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="tasks_assigne_801c9d_idx"
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to fix the bug",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bugs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bugs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a duplicate, link to the original bug",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="projects.bug",
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="linked_stories",
            field=models.ManyToManyField(
                blank=True,
                help_text="User stories related to this bug",
                related_name="linked_bugs",
                to="projects.userstory",
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bugs",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reported the bug",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_bugs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bug",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_bugs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["project", "status"], name="bugs_project_c94c41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["project", "severity"], name="bugs_project_96d4e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["project", "priority"], name="bugs_project_798b0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["assigned_to", "status"], name="bugs_assigne_f00bb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["reporter", "status"], name="bugs_reporte_a63920_idx"
            ),
        ),
    ]
