# Generated by Django 5.0.1 on 2025-12-09 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0011_bug_alter_notification_recipient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("feature_request", "Feature Request"),
                            ("question", "Question"),
                            ("documentation", "Documentation"),
                            ("performance", "Performance"),
                            ("security", "Security"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of issue",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("blocker", "Blocker"),
                            ("critical", "Critical"),
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("trivial", "Trivial"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fixed", "Fixed"),
                            ("wont_fix", "Won't Fix"),
                            ("duplicate", "Duplicate"),
                            ("invalid", "Invalid"),
                            ("works_as_designed", "Works as Designed"),
                            ("answered", "Answered"),
                            ("implemented", "Implemented"),
                        ],
                        help_text="Resolution when issue is closed/resolved",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        help_text="Environment where issue occurs (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing and filtering issues",
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Color-coded labels for visual grouping",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True,
                        help_text="Component or module related to this issue",
                        max_length=100,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Target date for issue resolution",
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the issue was resolved", null=True
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the issue was closed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to work on the issue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this is a duplicate, link to the original issue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="projects.issue",
                    ),
                ),
                (
                    "linked_bugs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bugs related to this issue",
                        related_name="linked_issues",
                        to="projects.bug",
                    ),
                ),
                (
                    "linked_stories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="User stories related to this issue",
                        related_name="linked_issues",
                        to="projects.userstory",
                    ),
                ),
                (
                    "linked_tasks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tasks related to this issue",
                        related_name="linked_issues",
                        to="projects.task",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reported the issue",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "watchers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users watching this issue for updates",
                        related_name="watched_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "db_table": "issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="When the work started")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the work ended (null if still in progress)",
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in minutes (calculated if end_time is set, or manually entered)",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of work performed"
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True, help_text="Whether this time is billable"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "bug",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bug this time log is for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="projects.bug",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_time_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        help_text="Issue this time log is for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="projects.issue",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        help_text="User story this time log is for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="projects.userstory",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task this time log is for",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="projects.task",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_time_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who logged this time",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "db_table": "time_logs",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Watcher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Watcher",
                "verbose_name_plural": "Watchers",
                "db_table": "watchers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("story_created", "Story Created"),
                            ("story_updated", "Story Updated"),
                            ("story_deleted", "Story Deleted"),
                            ("story_status_changed", "Story Status Changed"),
                            ("story_priority_changed", "Story Priority Changed"),
                            ("story_assigned", "Story Assigned"),
                            ("story_unassigned", "Story Unassigned"),
                            ("story_moved_to_sprint", "Story Moved to Sprint"),
                            ("story_removed_from_sprint", "Story Removed from Sprint"),
                            ("story_points_changed", "Story Points Changed"),
                            ("task_created", "Task Created"),
                            ("task_updated", "Task Updated"),
                            ("task_deleted", "Task Deleted"),
                            ("task_status_changed", "Task Status Changed"),
                            ("task_priority_changed", "Task Priority Changed"),
                            ("task_assigned", "Task Assigned"),
                            ("task_unassigned", "Task Unassigned"),
                            ("task_progress_updated", "Task Progress Updated"),
                            ("bug_created", "Bug Created"),
                            ("bug_updated", "Bug Updated"),
                            ("bug_deleted", "Bug Deleted"),
                            ("bug_status_changed", "Bug Status Changed"),
                            ("bug_severity_changed", "Bug Severity Changed"),
                            ("bug_resolved", "Bug Resolved"),
                            ("bug_closed", "Bug Closed"),
                            ("bug_reopened", "Bug Reopened"),
                            ("issue_created", "Issue Created"),
                            ("issue_updated", "Issue Updated"),
                            ("issue_deleted", "Issue Deleted"),
                            ("issue_status_changed", "Issue Status Changed"),
                            ("issue_resolved", "Issue Resolved"),
                            ("issue_closed", "Issue Closed"),
                            ("epic_created", "Epic Created"),
                            ("epic_updated", "Epic Updated"),
                            ("epic_deleted", "Epic Deleted"),
                            ("epic_status_changed", "Epic Status Changed"),
                            ("sprint_created", "Sprint Created"),
                            ("sprint_updated", "Sprint Updated"),
                            ("sprint_deleted", "Sprint Deleted"),
                            ("sprint_started", "Sprint Started"),
                            ("sprint_completed", "Sprint Completed"),
                            ("project_created", "Project Created"),
                            ("project_updated", "Project Updated"),
                            ("project_deleted", "Project Deleted"),
                            ("project_status_changed", "Project Status Changed"),
                            ("member_added", "Member Added"),
                            ("member_removed", "Member Removed"),
                            ("comment_added", "Comment Added"),
                            ("comment_updated", "Comment Updated"),
                            ("comment_deleted", "Comment Deleted"),
                            ("dependency_added", "Dependency Added"),
                            ("dependency_removed", "Dependency Removed"),
                            ("dependency_resolved", "Dependency Resolved"),
                            ("attachment_added", "Attachment Added"),
                            ("attachment_deleted", "Attachment Deleted"),
                            ("time_logged", "Time Logged"),
                            ("time_log_updated", "Time Log Updated"),
                            ("time_log_deleted", "Time Log Deleted"),
                            ("watcher_added", "Watcher Added"),
                            ("watcher_removed", "Watcher Removed"),
                            ("tag_added", "Tag Added"),
                            ("tag_removed", "Tag Removed"),
                            ("label_added", "Label Added"),
                            ("label_removed", "Label Removed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of the activity"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data about the activity (e.g., old_status, new_status, changed_fields)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this activity belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="activities_project_12e70e_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-created_at"],
                        name="activities_activit_b6cd50_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activities_user_id_7bdf29_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="activities_content_f3da64_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="activities_created_765ec9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EditHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "version",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Version number of this edit",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field values before the edit",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Field values after the edit",
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field names that were changed",
                    ),
                ),
                (
                    "diffs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Computed diffs for text fields (field_name -> diff_data)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment about this edit"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this edit history belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_histories",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made this edit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edit_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Edit History",
                "verbose_name_plural": "Edit Histories",
                "db_table": "edit_histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-version"],
                        name="edit_histor_content_1fc538_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="edit_histor_content_a72ea4_idx",
                    ),
                    models.Index(
                        fields=["project", "-created_at"],
                        name="edit_histor_project_7e3e5b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="edit_histor_user_id_9d3de3_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="edit_histor_created_288ebb_idx"
                    ),
                ],
                "unique_together": {("content_type", "object_id", "version")},
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "status"], name="issues_project_6804e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "issue_type"], name="issues_project_c854b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "priority"], name="issues_project_9b5555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["assigned_to", "status"], name="issues_assigne_7ac260_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["reporter", "status"], name="issues_reporte_5a9c93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "start_time"], name="time_logs_user_id_e21888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["story", "start_time"], name="time_logs_story_i_77704c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["task", "start_time"], name="time_logs_task_id_735de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["bug", "start_time"], name="time_logs_bug_id_b17762_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["issue", "start_time"], name="time_logs_issue_i_b01525_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("story__isnull", False),
                    ("task__isnull", False),
                    ("bug__isnull", False),
                    ("issue__isnull", False),
                    _connector="OR",
                ),
                name="time_log_must_have_work_item",
            ),
        ),
        migrations.AddIndex(
            model_name="watcher",
            index=models.Index(
                fields=["content_type", "object_id"], name="watchers_content_7caacf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watcher",
            index=models.Index(
                fields=["user", "created_at"], name="watchers_user_id_209216_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="watcher",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
