# Generated by Django 5.0.1 on 2025-12-09 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_issue_timelog_watcher_activity_edithistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this saved search", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                ("query", models.TextField(help_text="Search query string")),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Search filters (e.g., project, status, assignee, etc.)",
                    ),
                ),
                (
                    "content_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of content types to search (e.g., ['userstory', 'task'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this search was last used",
                        null=True,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this search has been used"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project to limit search to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who saved this search",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "db_table": "saved_searches",
                "ordering": ["-last_used_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="saved_searc_user_id_fc38f3_idx",
                    ),
                    models.Index(
                        fields=["user", "-last_used_at"],
                        name="saved_searc_user_id_f97bc6_idx",
                    ),
                    models.Index(
                        fields=["project", "-created_at"],
                        name="saved_searc_project_853ed8_idx",
                    ),
                ],
                "unique_together": {("user", "name")},
            },
        ),
    ]
