# Generated by Django 5.0.1 on 2025-12-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_savedsearch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
