# Generated by Django 5.0.1 on 2025-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom field values based on project configuration",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom field values based on project configuration",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom field values based on project configuration",
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom field values based on project configuration",
            ),
        ),
    ]
