# Generated by Django 5.0.1 on 2025-12-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_status_change_approval"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="statuschangeapproval",
            new_name="status_chan_project_c8d29d_idx",
            old_name="status_chan_project_status_idx",
        ),
        migrations.RenameIndex(
            model_name="statuschangeapproval",
            new_name="status_chan_content_ded85b_idx",
            old_name="status_chan_content_object_idx",
        ),
        migrations.RenameIndex(
            model_name="statuschangeapproval",
            new_name="status_chan_request_7c94d3_idx",
            old_name="status_chan_requested_status_idx",
        ),
        migrations.RenameIndex(
            model_name="statuschangeapproval",
            new_name="status_chan_approve_aaa3df_idx",
            old_name="status_chan_approver_status_idx",
        ),
    ]
