# Generated by Django 5.0.1 on 2025-12-09 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0017_rename_status_chan_project_status_idx_status_chan_project_c8d29d_idx_and_more",
        ),
        ("workflows", "0004_workflow_updated_by_workflowexecution_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(fields=["due_date"], name="bugs_due_dat_824eb5_idx"),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["project", "due_date"], name="bugs_project_4f3fa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(fields=["component"], name="bugs_compone_e5bd53_idx"),
        ),
        migrations.AddIndex(
            model_name="bug",
            index=models.Index(
                fields=["project", "component"], name="bugs_project_3c168f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="epic",
            index=models.Index(fields=["owner"], name="epics_owner_i_4b67c7_idx"),
        ),
        migrations.AddIndex(
            model_name="epic",
            index=models.Index(
                fields=["project", "owner"], name="epics_project_0013c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["due_date"], name="issues_due_dat_f0f017_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "due_date"], name="issues_project_557233_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["component"], name="issues_compone_857b12_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "component"], name="issues_project_8a16a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_due_dat_0359a9_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["component"], name="tasks_compone_de79e6_idx"),
        ),
        migrations.AddIndex(
            model_name="userstory",
            index=models.Index(
                fields=["due_date"], name="user_storie_due_dat_ccaf99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstory",
            index=models.Index(
                fields=["project", "due_date"], name="user_storie_project_104cb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstory",
            index=models.Index(
                fields=["component"], name="user_storie_compone_c3dccc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstory",
            index=models.Index(
                fields=["project", "component"], name="user_storie_project_b652d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstory",
            index=models.Index(
                fields=["story_type"], name="user_storie_story_t_b7c4d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userstory",
            index=models.Index(
                fields=["project", "story_type"], name="user_storie_project_1d9d9e_idx"
            ),
        ),
    ]
