# Generated by Django 5.0.1 on 2025-12-10 01:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0018_bug_bugs_due_dat_824eb5_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("sprint", "Sprint"),
                            ("story", "Story"),
                            ("task", "Task"),
                            ("epic", "Epic"),
                            ("user", "User"),
                        ],
                        help_text="What this budget applies to",
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="one_time",
                        help_text="Budget period",
                        max_length=20,
                    ),
                ),
                (
                    "budget_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total budgeted hours",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        help_text="Warning threshold percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, help_text="Start date of budget period", null=True
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, help_text="End date of budget period", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this budget active?"
                    ),
                ),
                (
                    "auto_alert",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create overtime records when exceeded",
                    ),
                ),
                (
                    "spent_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total hours spent (calculated)",
                        max_digits=10,
                    ),
                ),
                (
                    "remaining_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Remaining hours (calculated)",
                        max_digits=10,
                    ),
                ),
                (
                    "utilization_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Utilization percentage (calculated)",
                        max_digits=5,
                    ),
                ),
                (
                    "is_over_budget",
                    models.BooleanField(
                        default=False, help_text="Is over budget? (calculated)"
                    ),
                ),
                (
                    "is_warning_threshold_reached",
                    models.BooleanField(
                        default=False,
                        help_text="Has warning threshold been reached? (calculated)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_time_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_budgets",
                        to="projects.epic",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_budgets",
                        to="projects.project",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_budgets",
                        to="projects.sprint",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_budgets",
                        to="projects.userstory",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_budgets",
                        to="projects.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Budget",
                "verbose_name_plural": "Time Budgets",
                "db_table": "time_budgets",
            },
        ),
        migrations.CreateModel(
            name="OvertimeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours over budget",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "overtime_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage over budget",
                        max_digits=5,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="Start of period when overtime occurred"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End of period when overtime occurred"),
                ),
                (
                    "alert_sent",
                    models.BooleanField(
                        default=False, help_text="Has alert been sent?"
                    ),
                ),
                (
                    "alert_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When was alert sent?", null=True
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Has this overtime been resolved?"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When was this resolved?", null=True
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes on how overtime was resolved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_overtime_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "time_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_records",
                        to="projects.timebudget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overtime Record",
                "verbose_name_plural": "Overtime Records",
                "db_table": "overtime_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Webhook name", max_length=200)),
                ("url", models.URLField(help_text="Webhook URL")),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of events to trigger webhook"
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for webhook signature",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "webhooks",
            },
        ),
        migrations.CreateModel(
            name="BoardTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("project", "Project"), ("global", "Global")],
                        default="project",
                        help_text="Template scope",
                        max_length=20,
                    ),
                ),
                (
                    "board_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Board configuration (columns, swimlanes, filters, grouping, etc.)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier", max_length=50
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is a default template"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_board_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this template belongs to (null for global templates)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_templates",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_board_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board Template",
                "verbose_name_plural": "Board Templates",
                "db_table": "board_templates",
                "ordering": ["scope", "is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "scope"],
                        name="board_templ_project_6a380c_idx",
                    ),
                    models.Index(
                        fields=["scope", "is_default"],
                        name="board_templ_scope_d2571d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CardChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "title",
                    models.CharField(help_text="Checklist title", max_length=200),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text="List of checklist items: [{'id': 'uuid', 'text': 'string', 'completed': bool, 'order': int}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Checklist",
                "verbose_name_plural": "Card Checklists",
                "db_table": "card_checklists",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="card_checkl_content_def6d3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CardCoverImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "image",
                    models.ImageField(
                        help_text="Cover image for the card", upload_to="card_covers/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail version of the cover image",
                        null=True,
                        upload_to="card_covers/thumbnails/",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=True, help_text="Primary cover image"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Cover Image",
                "verbose_name_plural": "Card Cover Images",
                "db_table": "card_cover_images",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="card_cover__content_42a37f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("project", "Project"), ("global", "Global")],
                        default="project",
                        help_text="Template scope",
                        max_length=20,
                    ),
                ),
                (
                    "template_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template field values (title, description, acceptance_criteria, story_type, priority, etc.)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., 'bug', 'feature', 'task')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Template color (hex code)", max_length=7
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is a default template"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_card_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this template belongs to (null for global templates)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_templates",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_card_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Template",
                "verbose_name_plural": "Card Templates",
                "db_table": "card_templates",
                "ordering": ["scope", "is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "scope"],
                        name="card_templa_project_5bb2fd_idx",
                    ),
                    models.Index(
                        fields=["scope", "is_default"],
                        name="card_templa_scope_81e0d4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CardVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                        default="upvote",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Card Vote",
                "verbose_name_plural": "Card Votes",
                "db_table": "card_votes",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="card_votes_content_b8d7cf_idx",
                    ),
                    models.Index(fields=["user"], name="card_votes_user_id_b53675_idx"),
                ],
                "unique_together": {("content_type", "object_id", "user")},
            },
        ),
        migrations.CreateModel(
            name="FilterPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Preset name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Preset description"),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Filter rules (array of FilterRule objects)",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this preset is shared with team",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is a default preset"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this preset has been used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_filter_presets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this preset belongs to (null for global presets)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_presets",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this preset (null for shared presets)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Filter Preset",
                "verbose_name_plural": "Filter Presets",
                "db_table": "filter_presets",
                "ordering": ["is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "is_shared"],
                        name="filter_pres_project_85b369_idx",
                    ),
                    models.Index(
                        fields=["user", "is_shared"],
                        name="filter_pres_user_id_4a252c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GitHubIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "repository_owner",
                    models.CharField(
                        help_text="GitHub repository owner", max_length=255
                    ),
                ),
                (
                    "repository_name",
                    models.CharField(
                        help_text="GitHub repository name", max_length=255
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        help_text="GitHub access token (encrypted)", max_length=500
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this integration active?"
                    ),
                ),
                (
                    "sync_issues",
                    models.BooleanField(default=True, help_text="Sync GitHub issues"),
                ),
                (
                    "sync_commits",
                    models.BooleanField(default=False, help_text="Sync GitHub commits"),
                ),
                (
                    "sync_pull_requests",
                    models.BooleanField(default=False, help_text="Sync pull requests"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_github_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_github_integrations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Integration",
                "verbose_name_plural": "GitHub Integrations",
                "db_table": "project_github_integrations",
                "indexes": [
                    models.Index(
                        fields=["project", "is_active"],
                        name="project_git_project_c59a4e_idx",
                    )
                ],
                "unique_together": {("project", "repository_owner", "repository_name")},
            },
        ),
        migrations.CreateModel(
            name="JiraIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Jira base URL (e.g., https://yourcompany.atlassian.net)"
                    ),
                ),
                (
                    "project_key",
                    models.CharField(help_text="Jira project key", max_length=50),
                ),
                ("email", models.EmailField(help_text="Jira email", max_length=254)),
                (
                    "api_token",
                    models.CharField(
                        help_text="Jira API token (encrypted)", max_length=500
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this integration active?"
                    ),
                ),
                (
                    "sync_issues",
                    models.BooleanField(default=True, help_text="Sync Jira issues"),
                ),
                (
                    "auto_create",
                    models.BooleanField(
                        default=False, help_text="Auto-create Jira issues for stories"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_jira_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_jira_integrations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira Integration",
                "verbose_name_plural": "Jira Integrations",
                "db_table": "project_jira_integrations",
                "indexes": [
                    models.Index(
                        fields=["project", "is_active"],
                        name="project_jir_project_da65cb_idx",
                    )
                ],
                "unique_together": {("project", "base_url", "project_key")},
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Progress percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_milestones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_milestones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "db_table": "milestones",
                "ordering": ["project", "target_date"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="milestones_project_f51c6f_idx",
                    ),
                    models.Index(
                        fields=["project", "target_date"],
                        name="milestones_project_264193_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectLabelPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Label name", max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color code (e.g., #3b82f6)",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the label"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a default label for the project",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_label_presets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this label preset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_presets",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_label_presets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Label Preset",
                "verbose_name_plural": "Project Label Presets",
                "db_table": "project_label_presets",
                "ordering": ["is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "is_default"],
                        name="project_lab_project_ad9e0b_idx",
                    ),
                    models.Index(
                        fields=["project", "name"],
                        name="project_lab_project_6f4f39_idx",
                    ),
                ],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField(help_text="Search query string")),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, help_text="Search filters applied"
                    ),
                ),
                (
                    "content_types",
                    models.JSONField(
                        blank=True, default=list, help_text="Content types searched"
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(default=0, help_text="Number of results found"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project context (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this search",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
                "db_table": "search_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="search_hist_user_id_3ea0ad_idx",
                    ),
                    models.Index(
                        fields=["project", "-created_at"],
                        name="search_hist_project_9cc9bd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SlackIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="Slack webhook URL", null=True
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True,
                        help_text="Slack bot token (encrypted)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True, help_text="Default Slack channel", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this integration active?"
                    ),
                ),
                (
                    "notification_events",
                    models.JSONField(
                        default=list, help_text="Events to send notifications for"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_slack_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_slack_integrations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Integration",
                "verbose_name_plural": "Slack Integrations",
                "db_table": "project_slack_integrations",
                "indexes": [
                    models.Index(
                        fields=["project", "is_active"],
                        name="project_sla_project_2c50db_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for archiving"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive",
                        to="projects.userstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Archive",
                "verbose_name_plural": "Story Archives",
                "db_table": "story_archives",
                "indexes": [
                    models.Index(
                        fields=["archived_at"], name="story_archi_archive_3d1c82_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryClone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cloned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cloned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloned_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cloned_story",
                    models.OneToOneField(
                        help_text="The cloned story",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clone_source",
                        to="projects.userstory",
                    ),
                ),
                (
                    "original_story",
                    models.ForeignKey(
                        help_text="Original story that was cloned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clones",
                        to="projects.userstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Clone",
                "verbose_name_plural": "Story Clones",
                "db_table": "story_clones",
                "indexes": [
                    models.Index(
                        fields=["original_story"], name="story_clone_origina_9eb748_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("blocks", "Blocks"),
                            ("blocked_by", "Blocked By"),
                            ("relates_to", "Relates To"),
                            ("duplicates", "Duplicates"),
                            ("duplicated_by", "Duplicated By"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("depends_on", "Depends On"),
                            ("required_by", "Required By"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the link"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_story_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_links",
                        to="projects.project",
                    ),
                ),
                (
                    "source_story",
                    models.ForeignKey(
                        help_text="Story that has the link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="projects.userstory",
                    ),
                ),
                (
                    "target_story",
                    models.ForeignKey(
                        help_text="Story that is linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="projects.userstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Link",
                "verbose_name_plural": "Story Links",
                "db_table": "story_links",
                "indexes": [
                    models.Index(
                        fields=["project", "link_type"],
                        name="story_links_project_64cc8c_idx",
                    ),
                    models.Index(
                        fields=["source_story"], name="story_links_source__997043_idx"
                    ),
                    models.Index(
                        fields=["target_story"], name="story_links_target__71b652_idx"
                    ),
                ],
                "unique_together": {("source_story", "target_story", "link_type")},
            },
        ),
        migrations.CreateModel(
            name="StoryVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField(help_text="Version number")),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("acceptance_criteria", models.TextField()),
                ("status", models.CharField(max_length=50)),
                ("priority", models.CharField(max_length=20)),
                ("story_points", models.IntegerField(blank=True, null=True)),
                (
                    "story_data",
                    models.JSONField(
                        default=dict, help_text="Complete story data at this version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_story_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="projects.userstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Version",
                "verbose_name_plural": "Story Versions",
                "db_table": "story_versions",
                "ordering": ["story", "-version_number"],
                "indexes": [
                    models.Index(
                        fields=["story", "-version_number"],
                        name="story_versi_story_i_edcf3f_idx",
                    )
                ],
                "unique_together": {("story", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="TicketReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("jira", "Jira"),
                            ("gitlab", "GitLab"),
                            ("linear", "Linear"),
                            ("asana", "Asana"),
                            ("trello", "Trello"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        help_text="External ticket ID (e.g., issue number, ticket key)",
                        max_length=200,
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the external ticket",
                        max_length=500,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the external ticket",
                        max_length=300,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, help_text="Status in external system", max_length=50
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic syncing with external system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ticket_references",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_references",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Reference",
                "verbose_name_plural": "Ticket References",
                "db_table": "ticket_references",
                "indexes": [
                    models.Index(
                        fields=["project", "system"],
                        name="ticket_refe_project_46ba33_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="ticket_refe_content_ffb658_idx",
                    ),
                ],
                "unique_together": {
                    ("content_type", "object_id", "system", "ticket_id")
                },
            },
        ),
        migrations.AddIndex(
            model_name="timebudget",
            index=models.Index(
                fields=["project", "scope"], name="time_budget_project_6d43e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timebudget",
            index=models.Index(
                fields=["sprint", "scope"], name="time_budget_sprint__93d7a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timebudget",
            index=models.Index(
                fields=["story", "scope"], name="time_budget_story_i_b1bec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timebudget",
            index=models.Index(
                fields=["task", "scope"], name="time_budget_task_id_b50f3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timebudget",
            index=models.Index(
                fields=["epic", "scope"], name="time_budget_epic_id_1c9d35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timebudget",
            index=models.Index(
                fields=["user", "scope"], name="time_budget_user_id_6a8805_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timebudget",
            index=models.Index(
                fields=["is_active"], name="time_budget_is_acti_77df55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="overtimerecord",
            index=models.Index(
                fields=["time_budget", "resolved"],
                name="overtime_re_time_bu_ab7a02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="overtimerecord",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="overtime_re_period__bbe35b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="overtimerecord",
            index=models.Index(
                fields=["alert_sent"], name="overtime_re_alert_s_119611_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["project", "is_active"], name="webhooks_project_875d65_idx"
            ),
        ),
    ]
