# Generated by Django 5.0.1 on 2025-12-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_timebudget_overtimerecord_webhook_boardtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyversion',
            name='acceptance_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='acceptance_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
