# Generated by Django 5.0.1 on 2025-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_allow_null_acceptance_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique work item number within project",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="epic",
            name="number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique work item number within project",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique work item number within project",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="projectconfiguration",
            name="bug_prefix",
            field=models.CharField(
                default="BUG-",
                help_text="Prefix for bug numbers (e.g., BUG-)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectconfiguration",
            name="epic_prefix",
            field=models.CharField(
                default="EPIC-",
                help_text="Prefix for epic numbers (e.g., EPIC-)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectconfiguration",
            name="issue_prefix",
            field=models.CharField(
                default="ISSUE-",
                help_text="Prefix for issue numbers (e.g., ISSUE-)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectconfiguration",
            name="story_prefix",
            field=models.CharField(
                default="STORY-",
                help_text="Prefix for story numbers (e.g., STORY-)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectconfiguration",
            name="task_prefix",
            field=models.CharField(
                default="TASK-",
                help_text="Prefix for task numbers (e.g., TASK-)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique work item number within project (e.g., STORY-123)",
                max_length=50,
            ),
        ),
    ]
