# Generated by Django 5.0.1 on 2025-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_bug_number_epic_number_issue_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique work item number within project",
                max_length=50,
            ),
        ),
    ]
