# Generated by Django 5.0.1 on 2025-12-11 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_task_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfiguration",
            name="custom_roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom roles defined for this project (e.g., ['architect', 'devops', 'support'])",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles for this user in this project. Can include system roles and custom roles.",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_project_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "db_table": "project_members",
                "indexes": [
                    models.Index(
                        fields=["project", "user"],
                        name="project_mem_project_9e0a06_idx",
                    ),
                    models.Index(
                        fields=["project"], name="project_mem_project_e547cf_idx"
                    ),
                ],
                "unique_together": {("project", "user")},
            },
        ),
    ]
