# Generated by Django 5.0.1 on 2025-12-11 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0025_assign_projects_to_organizations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="projects_slug_25ccba_idx",
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "slug"], name="projects_organiz_6f7bbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization"], name="projects_organiz_896a0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner"], name="projects_owner_i_c299b3_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_at"], name="projects_created_40bcd1_idx"
            ),
        ),
    ]
