# Generated by Django 5.0.1 on 2025-12-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
