# Generated by Django 5.0.1 on 2025-12-13 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_allow_blank_slug"),
        ("workflows", "0004_workflow_updated_by_workflowexecution_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("output_directory", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("total_files", models.IntegerField(default=0)),
                ("total_size", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_generated_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_projects",
                        to="projects.project",
                    ),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_projects",
                        to="workflows.workflowexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Project",
                "verbose_name_plural": "Generated Projects",
                "db_table": "generated_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.CharField(db_index=True, max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.BigIntegerField(default=0)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "content_preview",
                    models.TextField(blank=True, help_text="First 1000 chars"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.generatedproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project File",
                "verbose_name_plural": "Project Files",
                "db_table": "project_files",
                "ordering": ["file_path"],
            },
        ),
        migrations.CreateModel(
            name="RepositoryExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("zip", "ZIP Archive"),
                            ("tar", "TAR Archive"),
                            ("tar.gz", "TAR GZIP Archive"),
                            ("github", "GitHub Repository"),
                            ("gitlab", "GitLab Repository"),
                        ],
                        max_length=20,
                    ),
                ),
                ("repository_name", models.CharField(blank=True, max_length=255)),
                ("repository_url", models.URLField(blank=True)),
                ("archive_path", models.CharField(blank=True, max_length=500)),
                ("archive_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("exporting", "Exporting"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="projects.generatedproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository Export",
                "verbose_name_plural": "Repository Exports",
                "db_table": "repository_exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="generatedproject",
            index=models.Index(
                fields=["project", "-created_at"], name="generated_p_project_ca96ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedproject",
            index=models.Index(fields=["status"], name="generated_p_status_9fc65c_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedproject",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="generated_p_created_b507d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["generated_project", "file_path"],
                name="project_fil_generat_a19cce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["file_type"], name="project_fil_file_ty_8620e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["content_hash"], name="project_fil_content_ac6185_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectfile",
            unique_together={("generated_project", "file_path")},
        ),
        migrations.AddIndex(
            model_name="repositoryexport",
            index=models.Index(
                fields=["generated_project", "-created_at"],
                name="repository__generat_489c6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryexport",
            index=models.Index(fields=["status"], name="repository__status_6b95b8_idx"),
        ),
        migrations.AddIndex(
            model_name="repositoryexport",
            index=models.Index(
                fields=["export_type"], name="repository__export__1a2340_idx"
            ),
        ),
    ]
