# Generated by Django 5.0.1 on 2025-12-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_generatedproject_projectfile_repositoryexport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Project description (max 5000 characters, plain text only)",
            ),
        ),
    ]
