# Generated by Django 4.2.26 on 2025-11-30 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google Gemini')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_url', models.URLField(blank=True)),
                ('organization_id', models.CharField(blank=True, max_length=255)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_day', models.IntegerField(default=10000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('failed_requests', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Platform',
                'verbose_name_plural': 'AI Platforms',
                'db_table': 'ai_platforms',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_time', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='integrations.aiplatform')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Usage',
                'verbose_name_plural': 'Platform Usage',
                'db_table': 'platform_usage',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['platform', '-timestamp'], name='platform_us_platfor_634bee_idx'), models.Index(fields=['-timestamp'], name='platform_us_timesta_b36bb1_idx')],
            },
        ),
    ]
