# Generated by Django 5.2.8 on 2025-11-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplatform",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
