# Generated by Django 5.2.8 on 2025-11-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_aiplatform_is_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aiplatform",
            old_name="name",
            new_name="platform_name",
        ),
    ]
