# Generated by Django 5.2.8 on 2025-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_rename_name_aiplatform_platform_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplatform",
            name="api_type",
            field=models.CharField(
                default="openai",
                help_text="Type of API structure used by this provider",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="default_model",
            field=models.CharField(
                default="gpt-4.1",
                help_text="Default LLM model used by this adapter",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="max_tokens",
            field=models.IntegerField(
                default=32000, help_text="Maximum tokens the platform supports"
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="supports_image_generation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="supports_json_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="supports_vision",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="timeout",
            field=models.IntegerField(default=30),
        ),
    ]
