# Generated by Django 5.2.8 on 2025-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_aiplatform_api_type_aiplatform_default_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiplatform",
            name="api_type",
            field=models.CharField(
                default="openai",
                help_text="Type of API structure used by this provider (openai/anthropic/google).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="aiplatform",
            name="default_model",
            field=models.CharField(
                default="gpt-4.1",
                help_text="Default model name used by this platform.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="aiplatform",
            name="max_tokens",
            field=models.IntegerField(
                default=32000,
                help_text="Maximum tokens the model supports for input + output.",
            ),
        ),
        migrations.AlterField(
            model_name="aiplatform",
            name="timeout",
            field=models.IntegerField(
                default=30, help_text="Default timeout (seconds)."
            ),
        ),
    ]
