# Generated by Django 5.2.8 on 2025-12-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_aiplatform_api_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiplatform',
            name='api_key',
            field=models.CharField(blank=True, help_text='Encrypted API key', max_length=500),
        ),
    ]
