# Generated by Django 5.0.1 on 2025-12-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_aiplatform_created_by_aiplatform_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiplatform",
            name="platform_name",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic Claude"),
                    ("google", "Google Gemini"),
                    ("openrouter", "OpenRouter"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
