# Generated by Django 5.0.1 on 2025-12-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_alter_aiplatform_platform_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplatform",
            name="conversation_id_field",
            field=models.CharField(
                blank=True,
                help_text="Field name for conversation ID in API requests (e.g., 'thread_id', 'conversation_id')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="conversation_id_path",
            field=models.CharField(
                blank=True,
                help_text="JSON path to conversation ID in API response (e.g., 'metadata.thread_id')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="conversation_strategy",
            field=models.CharField(
                choices=[
                    (
                        "stateless",
                        "Stateless - requires sending full message history each time",
                    ),
                    (
                        "thread_id",
                        "Thread ID - provider maintains context via thread/conversation ID (e.g., OpenAI Assistants API)",
                    ),
                    (
                        "session_id",
                        "Session ID - provider maintains context via session ID",
                    ),
                    (
                        "conversation_id",
                        "Conversation ID - provider maintains context via conversation ID (e.g., Gemini)",
                    ),
                    (
                        "assistant_thread",
                        "Assistant Thread - provider uses assistant + thread pattern (OpenAI Assistants)",
                    ),
                ],
                default="stateless",
                help_text="How this provider manages conversation context",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="returns_conversation_id",
            field=models.BooleanField(
                default=False,
                help_text="Whether API responses include conversation/thread ID we should extract",
            ),
        ),
    ]
