# Generated by Django 5.0.1 on 2025-12-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0010_aiplatform_conversation_id_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplatform",
            name="api_stateful",
            field=models.BooleanField(
                default=False,
                help_text="Whether API itself is stateful (server maintains conversation context)",
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="cost_optimization_notes",
            field=models.TextField(
                blank=True,
                help_text="Token cost implications, optimization strategies, recommendations for this provider",
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="identifier_extraction_paths",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON paths to extract each identifier type: {'thread_id': 'thread.id', 'session_id': 'session.id', etc.}",
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="metadata_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="All metadata fields provider returns: ['usage', 'model', 'finish_reason', 'created', 'id', etc.]",
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="provider_notes",
            field=models.TextField(
                blank=True,
                help_text="Comprehensive documentation: architecture (stateless/stateful), SDK support, identifiers, implementation details, cost implications",
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="sdk_session_support",
            field=models.BooleanField(
                default=False,
                help_text="Whether SDK provides session/conversation management (convenience wrapper)",
            ),
        ),
        migrations.AddField(
            model_name="aiplatform",
            name="supported_identifiers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of identifier types supported: ['thread_id', 'session_id', 'conversation_id', 'run_id', 'assistant_id']",
            ),
        ),
    ]
