# Generated by Django 5.0.1 on 2025-12-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
