# Generated by Django 4.2.26 on 2025-11-30 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentexecution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['agent_id'], name='agents_agent_i_cdfbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status'], name='agents_status_f5ff61_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['-created_at'], name='agents_created_a7b1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['agent', '-created_at'], name='agent_execu_agent_i_771607_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['user', '-created_at'], name='agent_execu_user_id_b2cdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(fields=['status'], name='agent_execu_status_28c835_idx'),
        ),
    ]
