# Generated by Django 5.0.1 on 2025-12-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_add_performance_indexes"),
        ("agents", "0002_initial"),
    ]

    operations = []
