# Generated by Django 5.0.1 on 2025-12-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_merge_0002_add_performance_indexes_0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agent",
            name="agents_status_invocations_idx",
        ),
        migrations.RemoveIndex(
            model_name="agent",
            name="agents_platform_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="agentexecution",
            name="agent_exec_user_status_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="agentexecution",
            name="agent_exec_platform_created_idx",
        ),
    ]
