# Generated by Django 5.0.1 on 2025-12-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_agents_status_invocations_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop all views that reference the tables we're modifying (SQLite requires this)
        migrations.RunSQL(
            sql="""
            DROP VIEW IF EXISTS agent_performance_summary;
            DROP VIEW IF EXISTS daily_system_metrics;
            DROP VIEW IF EXISTS user_activity_summary;
            """,
            reverse_sql="""
            -- Views will be recreated after migration
            """
        ),
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agents', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_executions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='agentexecution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_agent_executions', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='agentexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        # Recreate the views after table modifications
        migrations.RunSQL(
            sql="""
            CREATE VIEW IF NOT EXISTS agent_performance_summary AS
            SELECT 
                a.id AS agent_id,
                a.agent_id AS agent_identifier,
                a.name AS agent_name,
                COUNT(ae.id) AS total_executions,
                COUNT(CASE WHEN ae.status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN ae.status = 'failed' THEN 1 END) AS failed_executions,
                ROUND(
                    COUNT(CASE WHEN ae.status = 'completed' THEN 1 END) * 100.0 / NULLIF(COUNT(ae.id), 0),
                    2
                ) AS success_rate,
                AVG(ae.execution_time) AS avg_execution_time,
                SUM(ae.tokens_used) AS total_tokens_used,
                SUM(ae.cost) AS total_cost,
                MAX(ae.created_at) AS last_execution_at
            FROM agents a
            LEFT JOIN agent_executions ae ON a.id = ae.agent_id
            GROUP BY a.id, a.agent_id, a.name;
            
            CREATE VIEW IF NOT EXISTS daily_system_metrics AS
            SELECT 
                date(created_at) AS date,
                COUNT(*) AS total_agent_executions,
                COUNT(CASE WHEN status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN status = 'failed' THEN 1 END) AS failed_executions,
                SUM(tokens_used) AS total_tokens,
                SUM(cost) AS total_cost,
                AVG(execution_time) AS avg_execution_time
            FROM agent_executions
            WHERE created_at >= date('now', '-30 days')
            GROUP BY date(created_at)
            ORDER BY date DESC;
            
            CREATE VIEW IF NOT EXISTS user_activity_summary AS
            SELECT 
                u.id AS user_id,
                u.email,
                u.role,
                COUNT(DISTINCT ae.id) AS agent_executions_count,
                COUNT(DISTINCT ce.id) AS command_executions_count,
                COUNT(DISTINCT we.id) AS workflow_executions_count,
                SUM(ae.tokens_used) AS total_tokens_used,
                SUM(ae.cost) AS total_cost,
                MAX(
                    CASE 
                        WHEN COALESCE(ae.created_at, '1970-01-01') >= COALESCE(ce.started_at, '1970-01-01') 
                             AND COALESCE(ae.created_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ae.created_at
                        WHEN COALESCE(ce.started_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ce.started_at
                        ELSE we.created_at
                    END
                ) AS last_activity_at
            FROM users u
            LEFT JOIN agent_executions ae ON u.id = ae.user_id
            LEFT JOIN command_executions ce ON u.id = ce.user_id
            LEFT JOIN workflow_executions we ON u.id = we.user_id
            GROUP BY u.id, u.email, u.role;
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS agent_performance_summary;
            DROP VIEW IF EXISTS daily_system_metrics;
            DROP VIEW IF EXISTS user_activity_summary;
            """
        ),
    ]
