# Generated by Django 5.0.1 on 2025-12-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_performance_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("execute", "Execute"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("read", "Read"),
                ],
                max_length=20,
            ),
        ),
    ]
