# Generated by Django 5.0.1 on 2025-12-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowexecution",
            name="workflows_user_status_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowexecution",
            name="workflows_wf_status_started_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowstep",
            name="workflow_steps_exec_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="workflowstep",
            name="workflow_steps_exec_order_idx",
        ),
    ]
