# Generated by Django 4.2.26 on 2025-11-30 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Command Category',
                'verbose_name_plural': 'Command Categories',
                'db_table': 'command_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommandTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('template', models.TextField()),
                ('parameters', models.JSONField(default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='commands.commandcategory')),
            ],
            options={
                'verbose_name': 'Command Template',
                'verbose_name_plural': 'Command Templates',
                'db_table': 'command_templates',
                'indexes': [models.Index(fields=['slug'], name='command_tem_slug_72665d_idx'), models.Index(fields=['category', '-usage_count'], name='command_tem_categor_27a3f4_idx')],
            },
        ),
    ]
