# Generated by Django 5.2.8 on 2025-11-30 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtemplate',
            name='avg_execution_time',
            field=models.FloatField(default=0.0, help_text='Average execution time in seconds'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Estimated cost in USD to execute this command', max_digits=10),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='example_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Example input parameters and expected output preview'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='recommended_agent',
            field=models.ForeignKey(blank=True, help_text='Agent that works best with this command', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_commands', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='required_capabilities',
            field=models.JSONField(blank=True, default=list, help_text='List of required agent capabilities (e.g., CODE_GENERATION, LEGAL_REVIEW)'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='success_rate',
            field=models.FloatField(default=100.0, help_text='Percentage of successful executions (0-100)'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='total_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='total_successes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commandtemplate',
            name='parameters',
            field=models.JSONField(default=list, help_text='List of parameter definitions with name, type, required, description, example'),
        ),
        migrations.AlterField(
            model_name='commandtemplate',
            name='template',
            field=models.TextField(help_text='Template with parameter placeholders using {{param_name}} syntax'),
        ),
        migrations.AddIndex(
            model_name='commandtemplate',
            index=models.Index(fields=['-success_rate', '-usage_count'], name='command_tem_success_281b42_idx'),
        ),
        migrations.AddIndex(
            model_name='commandtemplate',
            index=models.Index(fields=['is_active', 'category'], name='command_tem_is_acti_9dc0cb_idx'),
        ),
    ]
