# Generated by Django 5.0.1 on 2025-12-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commands", "0002_add_performance_indexes"),
        ("commands", "0002_commandtemplate_avg_execution_time_and_more"),
    ]

    operations = []
