# Generated by Django 5.0.1 on 2025-12-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commands", "0003_merge_20251208_1402"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commandtemplate",
            name="commands_is_active_usage_idx",
        ),
        migrations.RemoveIndex(
            model_name="commandtemplate",
            name="commands_cat_active_success_idx",
        ),
        migrations.RemoveIndex(
            model_name="commandtemplate",
            name="commands_recommended_agent_idx",
        ),
    ]
