# Generated by Django 5.0.1 on 2025-12-08 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_remove_agent_agents_status_invocations_idx_and_more"),
        (
            "commands",
            "0004_remove_commandtemplate_commands_is_active_usage_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop views temporarily to avoid SQLite validation errors during schema changes
        migrations.RunSQL(
            sql="""
            DROP VIEW IF EXISTS agent_performance_summary;
            DROP VIEW IF EXISTS command_usage_statistics;
            DROP VIEW IF EXISTS daily_system_metrics;
            DROP VIEW IF EXISTS user_activity_summary;
            DROP VIEW IF EXISTS workflow_performance_summary;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.CreateModel(
            name="CommandExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_parameters",
                    models.JSONField(default=dict, help_text="Input parameters used"),
                ),
                (
                    "rendered_template",
                    models.TextField(blank=True, help_text="Rendered command template"),
                ),
                (
                    "output",
                    models.TextField(blank=True, help_text="Command output/result"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        default=0, help_text="Execution time in milliseconds"
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("cost", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Command Execution",
                "verbose_name_plural": "Command Executions",
                "db_table": "command_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="commandtemplate",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Command Template",
                "verbose_name_plural": "Command Templates",
            },
        ),
        migrations.RemoveIndex(
            model_name="commandtemplate",
            name="command_tem_success_281b42_idx",
        ),
        migrations.RemoveIndex(
            model_name="commandtemplate",
            name="command_tem_is_acti_9dc0cb_idx",
        ),
        migrations.RemoveField(
            model_name="commandtemplate",
            name="avg_execution_time",
        ),
        migrations.RemoveField(
            model_name="commandtemplate",
            name="success_rate",
        ),
        migrations.RemoveField(
            model_name="commandtemplate",
            name="total_failures",
        ),
        migrations.RemoveField(
            model_name="commandtemplate",
            name="total_successes",
        ),
        migrations.AddField(
            model_name="commandtemplate",
            name="estimated_duration",
            field=models.IntegerField(
                default=0, help_text="Estimated duration in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="commandtemplate",
            name="estimated_cost",
            field=models.FloatField(
                default=0.0, help_text="Estimated cost per execution"
            ),
        ),
        migrations.AddField(
            model_name="commandexecution",
            name="agent_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="command_executions",
                to="agents.agentexecution",
            ),
        ),
        migrations.AddField(
            model_name="commandexecution",
            name="command",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="commands.commandtemplate",
            ),
        ),
        migrations.AddField(
            model_name="commandexecution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="command_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="commandexecution",
            index=models.Index(
                fields=["command", "-started_at"], name="command_exe_command_8b1620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commandexecution",
            index=models.Index(
                fields=["user", "-started_at"], name="command_exe_user_id_af5717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commandexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="command_exe_status_cb79ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commandexecution",
            index=models.Index(
                fields=["started_at"], name="command_exe_started_7d8d89_idx"
            ),
        ),
        # Recreate views after schema changes
        migrations.RunSQL(
            sql="""
            CREATE VIEW agent_performance_summary AS
            SELECT 
                a.id AS agent_id,
                a.agent_id AS agent_identifier,
                a.name AS agent_name,
                COUNT(ae.id) AS total_executions,
                COUNT(CASE WHEN ae.status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN ae.status = 'failed' THEN 1 END) AS failed_executions,
                ROUND(
                    COUNT(CASE WHEN ae.status = 'completed' THEN 1 END) * 100.0 / NULLIF(COUNT(ae.id), 0),
                    2
                ) AS success_rate,
                AVG(ae.execution_time) AS avg_execution_time,
                SUM(ae.tokens_used) AS total_tokens_used,
                SUM(ae.cost) AS total_cost,
                MAX(ae.created_at) AS last_execution_at
            FROM agents a
            LEFT JOIN agent_executions ae ON a.id = ae.agent_id
            GROUP BY a.id, a.agent_id, a.name;
            
            CREATE VIEW command_usage_statistics AS
            SELECT 
                ct.id AS command_id,
                ct.name AS command_name,
                ct.category_id,
                cc.name AS category_name,
                COUNT(ce.id) AS total_executions,
                COUNT(CASE WHEN ce.status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN ce.status = 'failed' THEN 1 END) AS failed_executions,
                ROUND(
                    COUNT(CASE WHEN ce.status = 'completed' THEN 1 END) * 100.0 / NULLIF(COUNT(ce.id), 0),
                    2
                ) AS success_rate,
                AVG(ce.execution_time_ms) / 1000.0 AS avg_execution_time_seconds,
                SUM(ce.tokens_used) AS total_tokens_used,
                SUM(ce.cost) AS total_cost,
                MAX(ce.started_at) AS last_execution_at
            FROM command_templates ct
            LEFT JOIN command_categories cc ON ct.category_id = cc.id
            LEFT JOIN command_executions ce ON ct.id = ce.command_id
            GROUP BY ct.id, ct.name, ct.category_id, cc.name;
            
            CREATE VIEW daily_system_metrics AS
            SELECT 
                date(created_at) AS date,
                COUNT(*) AS total_agent_executions,
                COUNT(CASE WHEN status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN status = 'failed' THEN 1 END) AS failed_executions,
                SUM(tokens_used) AS total_tokens,
                SUM(cost) AS total_cost,
                AVG(execution_time) AS avg_execution_time
            FROM agent_executions
            WHERE created_at >= date('now', '-30 days')
            GROUP BY date(created_at)
            ORDER BY date DESC;
            
            CREATE VIEW user_activity_summary AS
            SELECT 
                u.id AS user_id,
                u.email,
                u.role,
                COUNT(DISTINCT ae.id) AS agent_executions_count,
                COUNT(DISTINCT ce.id) AS command_executions_count,
                COUNT(DISTINCT we.id) AS workflow_executions_count,
                SUM(ae.tokens_used) AS total_tokens_used,
                SUM(ae.cost) AS total_cost,
                MAX(
                    CASE 
                        WHEN COALESCE(ae.created_at, '1970-01-01') >= COALESCE(ce.started_at, '1970-01-01') 
                             AND COALESCE(ae.created_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ae.created_at
                        WHEN COALESCE(ce.started_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ce.started_at
                        ELSE we.created_at
                    END
                ) AS last_activity_at
            FROM users u
            LEFT JOIN agent_executions ae ON u.id = ae.user_id
            LEFT JOIN command_executions ce ON u.id = ce.user_id
            LEFT JOIN workflow_executions we ON u.id = we.user_id
            GROUP BY u.id, u.email, u.role;
            
            CREATE VIEW workflow_performance_summary AS
            SELECT 
                w.id AS workflow_id,
                w.name AS workflow_name,
                w.slug,
                COUNT(we.id) AS total_executions,
                COUNT(CASE WHEN we.status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN we.status = 'failed' THEN 1 END) AS failed_executions,
                COUNT(CASE WHEN we.status = 'running' THEN 1 END) AS running_executions,
                ROUND(
                    COUNT(CASE WHEN we.status = 'completed' THEN 1 END) * 100.0 / NULLIF(COUNT(we.id), 0),
                    2
                ) AS success_rate,
                AVG(
                    CASE 
                        WHEN we.completed_at IS NOT NULL AND we.started_at IS NOT NULL
                        THEN (julianday(we.completed_at) - julianday(we.started_at)) * 86400.0
                        ELSE NULL
                    END
                ) AS avg_execution_time_seconds,
                MAX(we.created_at) AS last_execution_at
            FROM workflows w
            LEFT JOIN workflow_executions we ON w.id = we.workflow_id
            GROUP BY w.id, w.name, w.slug;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
