# Generated by Django 5.0.1 on 2025-12-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0005_commandexecution_alter_commandtemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop views that reference the tables we're modifying (SQLite requires this)
        migrations.RunSQL(
            sql="""
            DROP VIEW IF EXISTS command_usage_statistics;
            DROP VIEW IF EXISTS user_activity_summary;
            """,
            reverse_sql="""
            -- Views will be recreated after migration
            """
        ),
        migrations.AddField(
            model_name='commandcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_command_categories', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='commandcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_command_categories', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='commandexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_command_executions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='commandexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='commandexecution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_command_executions', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_command_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='commandtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_command_templates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='commandcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commandcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commandtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commandtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        # Recreate the views after table modifications
        migrations.RunSQL(
            sql="""
            CREATE VIEW IF NOT EXISTS command_usage_statistics AS
            SELECT 
                ct.id AS command_id,
                ct.name AS command_name,
                ct.category_id,
                cc.name AS category_name,
                COUNT(ce.id) AS total_executions,
                COUNT(CASE WHEN ce.status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN ce.status = 'failed' THEN 1 END) AS failed_executions,
                ROUND(
                    COUNT(CASE WHEN ce.status = 'completed' THEN 1 END) * 100.0 / NULLIF(COUNT(ce.id), 0),
                    2
                ) AS success_rate,
                AVG(ce.execution_time_ms) / 1000.0 AS avg_execution_time_seconds,
                SUM(ce.tokens_used) AS total_tokens_used,
                SUM(ce.cost) AS total_cost,
                MAX(ce.started_at) AS last_execution_at
            FROM command_templates ct
            LEFT JOIN command_categories cc ON ct.category_id = cc.id
            LEFT JOIN command_executions ce ON ct.id = ce.command_id
            GROUP BY ct.id, ct.name, ct.category_id, cc.name;
            
            CREATE VIEW IF NOT EXISTS user_activity_summary AS
            SELECT 
                u.id AS user_id,
                u.email,
                u.role,
                COUNT(DISTINCT ae.id) AS agent_executions_count,
                COUNT(DISTINCT ce.id) AS command_executions_count,
                COUNT(DISTINCT we.id) AS workflow_executions_count,
                SUM(ae.tokens_used) AS total_tokens_used,
                SUM(ae.cost) AS total_cost,
                MAX(
                    CASE 
                        WHEN COALESCE(ae.created_at, '1970-01-01') >= COALESCE(ce.started_at, '1970-01-01') 
                             AND COALESCE(ae.created_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ae.created_at
                        WHEN COALESCE(ce.started_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ce.started_at
                        ELSE we.created_at
                    END
                ) AS last_activity_at
            FROM users u
            LEFT JOIN agent_executions ae ON u.id = ae.user_id
            LEFT JOIN command_executions ce ON u.id = ce.user_id
            LEFT JOIN workflow_executions we ON u.id = we.user_id
            GROUP BY u.id, u.email, u.role;
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS command_usage_statistics;
            DROP VIEW IF EXISTS user_activity_summary;
            """
        ),
    ]
