# Generated by Django 5.0.1 on 2025-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commands", "0006_commandcategory_created_by_and_more"),
    ]

    operations = [
        # Drop views that reference command_templates table before altering it
        migrations.RunSQL(
            sql="""
            DROP VIEW IF EXISTS command_usage_statistics;
            DROP VIEW IF EXISTS user_activity_summary;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddField(
            model_name="commandtemplate",
            name="avg_execution_time",
            field=models.FloatField(
                default=0.0, help_text="Average execution time in seconds"
            ),
        ),
        migrations.AddField(
            model_name="commandtemplate",
            name="success_rate",
            field=models.FloatField(
                default=100.0, help_text="Percentage of successful executions (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="commandtemplate",
            name="total_failures",
            field=models.IntegerField(
                default=0, help_text="Total number of failed executions"
            ),
        ),
        migrations.AddField(
            model_name="commandtemplate",
            name="total_successes",
            field=models.IntegerField(
                default=0, help_text="Total number of successful executions"
            ),
        ),
        migrations.AddIndex(
            model_name="commandtemplate",
            index=models.Index(fields=['-success_rate', '-usage_count'], name='cmd_tmpl_success_idx'),
        ),
        migrations.AddIndex(
            model_name="commandtemplate",
            index=models.Index(fields=['category', 'is_active', '-success_rate'], name='cmd_cat_act_success_idx'),
        ),
        # Recreate views after schema changes
        migrations.RunSQL(
            sql="""
            CREATE VIEW IF NOT EXISTS command_usage_statistics AS
            SELECT 
                ct.id AS command_id,
                ct.name AS command_name,
                ct.category_id,
                cc.name AS category_name,
                COUNT(ce.id) AS total_executions,
                COUNT(CASE WHEN ce.status = 'completed' THEN 1 END) AS successful_executions,
                COUNT(CASE WHEN ce.status = 'failed' THEN 1 END) AS failed_executions,
                ROUND(
                    COUNT(CASE WHEN ce.status = 'completed' THEN 1 END) * 100.0 / NULLIF(COUNT(ce.id), 0),
                    2
                ) AS success_rate,
                AVG(ce.execution_time_ms) / 1000.0 AS avg_execution_time_seconds,
                SUM(ce.tokens_used) AS total_tokens_used,
                SUM(ce.cost) AS total_cost,
                MAX(ce.started_at) AS last_execution_at
            FROM command_templates ct
            LEFT JOIN command_categories cc ON ct.category_id = cc.id
            LEFT JOIN command_executions ce ON ct.id = ce.command_id
            GROUP BY ct.id, ct.name, ct.category_id, cc.name;
            
            CREATE VIEW IF NOT EXISTS user_activity_summary AS
            SELECT 
                u.id AS user_id,
                u.email,
                u.role,
                COUNT(DISTINCT ae.id) AS agent_executions_count,
                COUNT(DISTINCT ce.id) AS command_executions_count,
                COUNT(DISTINCT we.id) AS workflow_executions_count,
                SUM(ae.tokens_used) AS total_tokens_used,
                SUM(ae.cost) AS total_cost,
                MAX(
                    CASE 
                        WHEN COALESCE(ae.created_at, '1970-01-01') >= COALESCE(ce.started_at, '1970-01-01') 
                             AND COALESCE(ae.created_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ae.created_at
                        WHEN COALESCE(ce.started_at, '1970-01-01') >= COALESCE(we.created_at, '1970-01-01')
                        THEN ce.started_at
                        ELSE we.created_at
                    END
                ) AS last_activity_at
            FROM users u
            LEFT JOIN agent_executions ae ON u.id = ae.user_id
            LEFT JOIN command_executions ce ON u.id = ce.user_id
            LEFT JOIN workflow_executions we ON u.id = we.user_id
            GROUP BY u.id, u.email, u.role;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
