# Generated by Django 5.0.1 on 2025-12-08 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_epic_userstory_epic_epic_epics_project_ea7cbe_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notify_workflow_completion", models.BooleanField(default=True)),
                ("notify_command_execution", models.BooleanField(default=False)),
                ("notify_system_alerts", models.BooleanField(default=True)),
                ("notify_project_updates", models.BooleanField(default=False)),
                ("notify_daily_summary", models.BooleanField(default=False)),
                ("notify_weekly_summary", models.BooleanField(default=True)),
                ("email_address", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Notification Settings",
                "verbose_name_plural": "Email Notification Settings",
                "db_table": "email_notification_settings",
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("secret", models.CharField(blank=True, max_length=500)),
                ("trigger_on_workflow_completion", models.BooleanField(default=False)),
                ("trigger_on_command_execution", models.BooleanField(default=False)),
                ("trigger_on_project_update", models.BooleanField(default=False)),
                ("trigger_on_system_alert", models.BooleanField(default=False)),
                ("custom_events", models.JSONField(blank=True, default=list)),
                (
                    "method",
                    models.CharField(
                        choices=[("POST", "POST"), ("PUT", "PUT"), ("PATCH", "PATCH")],
                        default="POST",
                        max_length=10,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.IntegerField(default=3)),
                ("timeout_seconds", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "db_table": "webhook_endpoints",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations_external.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "db_table": "webhook_deliveries",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("repository_owner", models.CharField(max_length=200)),
                ("repository_name", models.CharField(max_length=200)),
                ("access_token", models.CharField(max_length=500)),
                ("webhook_secret", models.CharField(blank=True, max_length=500)),
                ("auto_create_issues", models.BooleanField(default=False)),
                ("auto_sync_prs", models.BooleanField(default=False)),
                ("sync_workflows", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_integrations",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Integration",
                "verbose_name_plural": "GitHub Integrations",
                "db_table": "github_integrations",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="github_inte_user_id_b233e6_idx",
                    ),
                    models.Index(
                        fields=["repository_owner", "repository_name"],
                        name="github_inte_reposit_457b7e_idx",
                    ),
                ],
                "unique_together": {("repository_owner", "repository_name", "user")},
            },
        ),
        migrations.CreateModel(
            name="SlackIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workspace_name", models.CharField(max_length=200)),
                ("channel_id", models.CharField(max_length=200)),
                ("channel_name", models.CharField(max_length=200)),
                ("bot_token", models.CharField(max_length=500)),
                ("notify_workflow_completion", models.BooleanField(default=True)),
                ("notify_command_execution", models.BooleanField(default=False)),
                ("notify_system_alerts", models.BooleanField(default=True)),
                ("notify_project_updates", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Integration",
                "verbose_name_plural": "Slack Integrations",
                "db_table": "slack_integrations",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="slack_integ_user_id_47b88d_idx",
                    ),
                    models.Index(
                        fields=["workspace_name", "channel_id"],
                        name="slack_integ_workspa_712e1a_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["user", "is_active"], name="webhook_end_user_id_1ace08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["is_active", "trigger_on_workflow_completion"],
                name="webhook_end_is_acti_759f17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["endpoint", "-triggered_at"],
                name="webhook_del_endpoin_1c6ebb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "-triggered_at"], name="webhook_del_status_f63d65_idx"
            ),
        ),
    ]
