# Generated by Django 5.0.1 on 2025-12-10 01:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations_external", "0002_emailnotificationsettings_created_by_and_more"),
        ("projects", "0018_bug_bugs_due_dat_824eb5_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "jira_url",
                    models.URLField(
                        help_text="Jira instance URL (e.g., https://yourcompany.atlassian.net)"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Jira username or email", max_length=200
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        help_text="Jira API token (encrypted in future)", max_length=500
                    ),
                ),
                (
                    "project_key",
                    models.CharField(
                        help_text="Jira project key (e.g., PROJ)", max_length=50
                    ),
                ),
                (
                    "auto_create_issues",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically create Jira issues from stories",
                    ),
                ),
                (
                    "auto_sync_status",
                    models.BooleanField(
                        default=False, help_text="Sync status changes between systems"
                    ),
                ),
                (
                    "sync_comments",
                    models.BooleanField(
                        default=True, help_text="Sync comments between systems"
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        default="Story",
                        help_text="Default Jira issue type",
                        max_length=50,
                    ),
                ),
                (
                    "priority_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map story priorities to Jira priorities",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_jira_integrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_integrations",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_jira_integrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira Integration",
                "verbose_name_plural": "Jira Integrations",
                "db_table": "jira_integrations",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="jira_integr_user_id_f3bf87_idx",
                    ),
                    models.Index(
                        fields=["jira_url", "project_key"],
                        name="jira_integr_jira_ur_03b2bb_idx",
                    ),
                ],
                "unique_together": {("jira_url", "project_key", "user")},
            },
        ),
    ]
