# Generated by Django 5.0.1 on 2025-12-11 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_apikey_created_by_apikey_updated_at_and_more"),
        ("organizations", "0001_initial"),  # Ensure organizations app is migrated first
    ]

    operations = [
        # Drop the view that references the users table before we alter it
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS user_activity_summary;",
            reverse_sql="-- View will be recreated by monitoring migrations"
        ),
        # Fix foreign key constraints - set epic owners to NULL if user doesn't exist
        migrations.RunSQL(
            sql="""
            UPDATE epics 
            SET owner_id = NULL 
            WHERE owner_id NOT IN (SELECT id FROM users);
            """,
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary organization this user belongs to. Super admins can access all organizations.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                default="viewer",
                help_text="System-level role. Use RoleService for validation.",
                max_length=50,
            ),
        ),
    ]
