# Generated by Django 5.0.1 on 2025-12-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_add_organization_usage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="organizationusage",
            new_name="organizatio_organiz_b6ae3f_idx",
            old_name="organizatio_organiz_usage_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationusage",
            new_name="organizatio_organiz_742d70_idx",
            old_name="organizatio_organiz_usage_t_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationusage",
            new_name="organizatio_month_f57460_idx",
            old_name="organizatio_month_yea_idx",
        ),
    ]
