# Generated by Django 5.0.1 on 2025-12-15 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0003_rename_organizatio_organiz_usage_idx_organizatio_organiz_b6ae3f_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Billing amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("upgrade", "Upgrade"),
                            ("downgrade", "Downgrade"),
                            ("refund", "Refund"),
                        ],
                        help_text="Type of billing transaction",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe invoice ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe payment intent ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was completed", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional billing metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Billing Record",
                "verbose_name_plural": "Billing Records",
                "db_table": "billing_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text='Unique feature code (e.g., "ai.custom_agents")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the feature", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("users", "User Management"),
                            ("projects", "Project Management"),
                            ("ai", "AI & Automation"),
                            ("integrations", "Integrations"),
                            ("analytics", "Analytics & Reporting"),
                            ("support", "Support & Collaboration"),
                            ("security", "Security & Compliance"),
                        ],
                        db_index=True,
                        help_text="Feature category",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean"),
                            ("count", "Count Limit"),
                            ("usage", "Usage Limit"),
                            ("unlimited", "Unlimited"),
                        ],
                        help_text="Type of feature: boolean, count, usage, or unlimited",
                        max_length=20,
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default value for this feature",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_deprecated",
                    models.BooleanField(
                        default=False, help_text="Whether this feature is deprecated"
                    ),
                ),
                (
                    "deprecated_at",
                    models.DateTimeField(
                        blank=True, help_text="When feature was deprecated", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional feature metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "db_table": "features",
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier_code",
                    models.CharField(
                        db_index=True,
                        help_text="Current tier code (denormalized from plan)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Subscription status",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        help_text="Billing cycle",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When subscription started"),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(help_text="Current billing period start"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(help_text="Current billing period end"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription was cancelled",
                        null=True,
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, help_text="Whether to cancel at period end"
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe subscription ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe customer ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional subscription metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier_code",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        help_text="Subscription tier code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        help_text="Display name for the tier", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "monthly_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly subscription price in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual subscription price in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this plan is currently available",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Order for display in UI"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional plan metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plans",
                "ordering": ["display_order", "tier_code"],
            },
        ),
        migrations.CreateModel(
            name="TierFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier_code",
                    models.CharField(
                        db_index=True, help_text="Subscription tier code", max_length=50
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="Feature value for this tier (boolean, number, or null for unlimited)"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this feature is enabled for this tier",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tier Feature",
                "verbose_name_plural": "Tier Features",
                "db_table": "tier_features",
            },
        ),
        migrations.AddField(
            model_name="organizationusage",
            name="limit_value",
            field=models.IntegerField(
                blank=True,
                help_text="Limit value for this month (denormalized from subscription tier)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationusage",
            name="warning_sent",
            field=models.BooleanField(
                default=False, help_text="Whether usage warning email has been sent"
            ),
        ),
        migrations.AddField(
            model_name="organizationusage",
            name="warning_threshold",
            field=models.IntegerField(
                blank=True,
                help_text="Warning threshold (typically 80% of limit)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="max_projects",
            field=models.IntegerField(
                default=5,
                help_text="Maximum number of projects allowed (denormalized from subscription)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="max_users",
            field=models.IntegerField(
                default=10,
                help_text="Maximum number of users allowed (denormalized from subscription)",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="subscription_tier",
            field=models.CharField(
                default="trial",
                help_text="Subscription tier: trial, basic, professional, enterprise (denormalized from active subscription)",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="organizationusage",
            index=models.Index(
                fields=["organization", "usage_type", "warning_sent"],
                name="organizatio_organiz_d7efa1_idx",
            ),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_records",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["code"], name="features_code_872a60_idx"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["category"], name="features_categor_c4ad65_idx"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["is_active"], name="features_is_acti_f7d7c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["feature_type"], name="features_feature_083d3c_idx"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_records",
                to="organizations.subscription",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="active_subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently active subscription",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_organization",
                to="organizations.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["tier_code"], name="subscriptio_tier_co_f622be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active"], name="subscriptio_is_acti_4d4352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["display_order"], name="subscriptio_display_a174d6_idx"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                help_text="Subscription plan",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="organizations.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="tierfeature",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier_mappings",
                to="organizations.feature",
            ),
        ),
        migrations.AddIndex(
            model_name="billingrecord",
            index=models.Index(
                fields=["subscription", "status"], name="billing_rec_subscri_b865d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingrecord",
            index=models.Index(
                fields=["organization", "status"], name="billing_rec_organiz_3fe5f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingrecord",
            index=models.Index(fields=["status"], name="billing_rec_status_67ff57_idx"),
        ),
        migrations.AddIndex(
            model_name="billingrecord",
            index=models.Index(
                fields=["stripe_invoice_id"], name="billing_rec_stripe__e2ae83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingrecord",
            index=models.Index(
                fields=["due_date"], name="billing_rec_due_dat_d44954_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["organization", "status"], name="subscriptio_organiz_4f7e3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="subscriptio_status_572d44_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["tier_code"], name="subscriptio_tier_co_51d27d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="subscriptio_stripe__aa726e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="subscriptio_current_0ac39a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tierfeature",
            index=models.Index(
                fields=["tier_code", "feature"], name="tier_featur_tier_co_26f3be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tierfeature",
            index=models.Index(
                fields=["tier_code"], name="tier_featur_tier_co_60a07b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tierfeature",
            index=models.Index(
                fields=["feature"], name="tier_featur_feature_59e8b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tierfeature",
            unique_together={("tier_code", "feature")},
        ),
    ]
