# Generated by Django 5.0.1 on 2025-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0004_billingrecord_feature_subscription_subscriptionplan_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tierfeature",
            name="value",
            field=models.JSONField(
                blank=True,
                help_text="Feature value for this tier (boolean, number, or null for unlimited)",
                null=True,
            ),
        ),
    ]
