# Generated by Django 5.0.1 on 2025-12-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_created_by_message_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="ai_conversation_id",
            field=models.CharField(
                blank=True,
                help_text="AI provider's conversation/thread ID for maintaining context on their side",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="ai_conversation_summary",
            field=models.TextField(
                blank=True,
                help_text="Summary of older messages for context without sending full history",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_summary_message_count",
            field=models.IntegerField(
                default=0, help_text="Number of messages when summary was last updated"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="max_recent_messages",
            field=models.IntegerField(
                default=10,
                help_text="Maximum recent messages to include in each request (sliding window)",
            ),
        ),
    ]
