# Generated by Django 5.0.1 on 2025-12-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_ai_conversation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="ai_conversation_id",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="ai_conversation_summary",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="last_summary_message_count",
        ),
        migrations.AddField(
            model_name="conversation",
            name="ai_provider_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific conversation context (thread_id, session_id, conversation_id, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="max_recent_messages",
            field=models.IntegerField(
                default=20,
                help_text="Maximum recent messages to send for stateless providers (sliding window)",
            ),
        ),
    ]
