# Generated by Django 5.0.1 on 2025-12-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_conversation_ai_conversation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="cost_tracking",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cost tracking: {total_cost: 0.05, currency: 'USD', per_message_costs: [{message_id: '...', cost: 0.01}], last_updated: '...'}",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="extracted_identifiers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="All extracted identifiers: {thread_id: '...', session_id: '...', conversation_id: '...', run_id: '...', assistant_id: '...', etc.}",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="provider_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete provider response metadata: {message_id: {usage: {...}, model: '...', finish_reason: '...', etc.}}",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="token_usage_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Token usage per message: [{message_id: '...', input_tokens: 100, output_tokens: 50, total_tokens: 150, timestamp: '...'}]",
            ),
        ),
    ]
