# Generated by Django 5.0.1 on 2025-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_conversation_cost_tracking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="conversation_summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated summary of older conversation history (for maintaining context in long conversations)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="summarize_at_message_count",
            field=models.IntegerField(
                default=30,
                help_text="Trigger summarization when conversation reaches this many messages",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="summarize_at_token_count",
            field=models.IntegerField(
                default=8000,
                help_text="Trigger summarization when conversation tokens exceed this count (approximate)",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="summary_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Summary metadata: {last_summarized_at: '...', messages_summarized_count: 10, summary_version: 1, summary_tokens: 150}",
            ),
        ),
    ]
