# Generated by Django 5.0.1 on 2025-12-14 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_add_code_context_tracking_fields"),
        (
            "organizations",
            "0003_rename_organizatio_organiz_usage_idx_organizatio_organiz_b6ae3f_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(
                help_text="Auto-generated from first message or user-set. Can be edited by user.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="MemberConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional title for the conversation. Defaults to other participant's name if not set.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_conversations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "participant1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_conversations_as_participant1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_conversations_as_participant2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of file references/URLs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.memberconversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_member_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="memberconversation",
            index=models.Index(
                fields=["participant1", "-updated_at"],
                name="chat_member_partici_5b3eb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memberconversation",
            index=models.Index(
                fields=["participant2", "-updated_at"],
                name="chat_member_partici_cf1ccd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="memberconversation",
            index=models.Index(
                fields=["organization", "-updated_at"],
                name="chat_member_organiz_d164c6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="memberconversation",
            constraint=models.UniqueConstraint(
                fields=("participant1", "participant2", "organization"),
                name="unique_member_conversation",
            ),
        ),
        migrations.AddIndex(
            model_name="membermessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_member_convers_08c64b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membermessage",
            index=models.Index(
                fields=["sender", "created_at"], name="chat_member_sender__bb25f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membermessage",
            index=models.Index(
                fields=["is_read", "created_at"], name="chat_member_is_read_912455_idx"
            ),
        ),
    ]
