# Generated by Django 5.0.1 on 2025-12-14 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_conversation_title_memberconversation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membermessage",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, help_text="When message was delivered", null=True
            ),
        ),
        migrations.AddField(
            model_name="membermessage",
            name="is_delivered",
            field=models.BooleanField(
                default=False, help_text="Message has been delivered to recipient"
            ),
        ),
        migrations.AlterField(
            model_name="membermessage",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Message has been read by recipient"
            ),
        ),
        migrations.AlterField(
            model_name="membermessage",
            name="read_at",
            field=models.DateTimeField(
                blank=True, help_text="When message was read", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="membermessage",
            index=models.Index(
                fields=["is_delivered", "created_at"],
                name="chat_member_is_deli_f9e563_idx",
            ),
        ),
    ]
